import base64
import json
import shutil
import uuid
from pathlib import Path
from typing import Iterable, List, Optional

from .config import EXPECTED_PACKS

PACK_ICON_PNG_BASE64 = (
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR4nGNgYAAAAAMA"
    "ASsJTYQAAAAASUVORK5CYII="
)


def expected_pack_names() -> List[str]:
    names = []
    for pack in EXPECTED_PACKS:
        if isinstance(pack, dict):
            name = pack.get("name")
            if name:
                names.append(name)
        else:
            names.append(pack[0])
    return names


def check_missing_packs(root_path: Path) -> List[str]:
    missing = []
    for name in expected_pack_names():
        if not (root_path / name).is_dir():
            missing.append(name)
    return missing


def find_template_pack(root_path: Path) -> Optional[Path]:
    for name in expected_pack_names():
        pack_dir = root_path / name
        if not pack_dir.is_dir():
            continue
        if (pack_dir / "manifest.json").is_file() or (pack_dir / "pack_icon.png").is_file():
            return pack_dir
    return None


def create_missing_packs(root_path: Path, missing_names: Iterable[str]) -> List[Path]:
    template_pack = find_template_pack(root_path)
    created = []
    for name in missing_names:
        created.append(create_pack(root_path, name, template_pack))
    return created


def create_pack(root_path: Path, name: str, template_pack: Optional[Path]) -> Path:
    pack_dir = root_path / name
    pack_dir.mkdir(parents=True, exist_ok=True)

    template_manifest = template_pack / "manifest.json" if template_pack else None
    template_icon = template_pack / "pack_icon.png" if template_pack else None

    manifest_path = pack_dir / "manifest.json"
    icon_path = pack_dir / "pack_icon.png"

    if template_manifest and template_manifest.is_file():
        shutil.copy2(template_manifest, manifest_path)
        manifest = _load_manifest(manifest_path)
        manifest = _normalize_manifest(manifest, name)
        _write_manifest(manifest_path, manifest)
    else:
        manifest = _create_manifest(name)
        _write_manifest(manifest_path, manifest)

    if template_icon and template_icon.is_file():
        shutil.copy2(template_icon, icon_path)
    else:
        _write_placeholder_icon(icon_path)

    return pack_dir


def _load_manifest(path: Path) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {}


def _write_manifest(path: Path, manifest: dict) -> None:
    path.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


def _normalize_manifest(manifest: dict, name: str) -> dict:
    if not isinstance(manifest, dict):
        return _create_manifest(name)

    header = manifest.setdefault("header", {})
    if not isinstance(header, dict):
        header = {}
        manifest["header"] = header

    header["name"] = name
    header.setdefault("description", f"{name} (generated by goldstar)")
    header["uuid"] = str(uuid.uuid4())
    header.setdefault("version", [1, 0, 0])
    header.setdefault("min_engine_version", [1, 20, 0])

    modules = manifest.setdefault(
        "modules",
        [
            {
                "type": "resources",
                "uuid": str(uuid.uuid4()),
                "version": [1, 0, 0],
            }
        ],
    )

    if isinstance(modules, list):
        for module in modules:
            if not isinstance(module, dict):
                continue
            module.setdefault("type", "resources")
            module.setdefault("version", [1, 0, 0])
            module["uuid"] = str(uuid.uuid4())

    return manifest


def _create_manifest(name: str) -> dict:
    return {
        "format_version": 2,
        "header": {
            "name": name,
            "description": f"{name} (generated by goldstar)",
            "uuid": str(uuid.uuid4()),
            "version": [1, 0, 0],
            "min_engine_version": [1, 20, 0],
        },
        "modules": [
            {
                "type": "resources",
                "uuid": str(uuid.uuid4()),
                "version": [1, 0, 0],
            }
        ],
    }


def _write_placeholder_icon(path: Path) -> None:
    data = base64.b64decode(PACK_ICON_PNG_BASE64)
    path.write_bytes(data)
